// <auto-generated />
using System;
using GerenciadorRecebiveisAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorRecebiveisAPI.Migrations
{
    [DbContext(typeof(RecebiveisDbContext))]
    partial class RecebiveisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.Checkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Desagio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Taxa")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId")
                        .IsUnique();

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<decimal>("Faturamento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Ramo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.Carrinho", b =>
                {
                    b.HasOne("GerenciadorRecebiveisAPI.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.Checkout", b =>
                {
                    b.HasOne("GerenciadorRecebiveisAPI.Models.Carrinho", "Carrinho")
                        .WithOne("Checkout")
                        .HasForeignKey("GerenciadorRecebiveisAPI.Models.Checkout", "CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");
                });

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.NotaFiscal", b =>
                {
                    b.HasOne("GerenciadorRecebiveisAPI.Models.Carrinho", null)
                        .WithMany("NotasFiscais")
                        .HasForeignKey("CarrinhoId");
                });

            modelBuilder.Entity("GerenciadorRecebiveisAPI.Models.Carrinho", b =>
                {
                    b.Navigation("Checkout");

                    b.Navigation("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
